# This is a basic workflow to help you get started with Actions

name: CI & CD for java on azure webapp

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ My ]

env:
  AZURE_WEBAPP_NAME: Java-Mysql-Simple-Login-Web-application  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }} # set this to the path to your web app project
  JAVA_VERSION: '1.8'                # set this to the node version to use
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Java 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Analyze with SonarCloud
      #run: mvn -B verify sonar:sonar -Dsonar.projectKey=Java-Mysql-Simple-Login-Web-application -Dsonar.organization=jassu2017 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_CLOUD_TOKEN
      run: mvn clean org.sonarsource.scanner.maven:sonar package sonar:soanr -Dsonar.projectKey=Java-Mysql-Simple-Login-Web-application -Dsonar.organization=jassu2017 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_CLOUD_TOKEN
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
        
    #- name: SonarCloud Scan
     # uses: sonarsource/sonarcloud-github-action@master
      #env:
       # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
        
    
    - name: Build with maven
      run: mvn -B package --file pom.xml
      #run: org.sonarsource.scanner.maven:sonar
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
         # Artifact name
        name: 'LoginWebApp.war'
    # A file, directory or wildcard pattern that describes what to upload
        path: ${{github.workspace}}
        
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
      with:
    # Artifact name
        name: 'LoginWebApp.war'
    # Destination path
        path: ${{github.workspace}}target/'*.war'
        
    - name: Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
         # Name of the Azure Web App
         app-name: ${{ env.AZURE_WEBAPP_NAME }}
         # Applies to Web App only: Publish profile (*.publishsettings) file contents with Web Deploy secrets
         publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
         # Enter an existing Slot other than the Production slot
         #slot-name: Dev
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
         package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/target/*.war'
           # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
        #images: 
           # Applies to Web App Containers only: Path of the Docker-Compose file. Should be a fully qualified path or relative to the default working directory. Required for multi-container scenario
        #configuration-file: # optional
         # Enter the start up command. For ex. dotnet run or dotnet run
        #startup-command: # optional
        
    
      
    
