name: Maven Publish to GITHUB Package

on:
  push:
    branches: [ Feature-Github-Pkg ]
  pull_request:
    branches: [ Feature-Github-Pkg ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Deploy to Github Package Registry
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
      run: |
        echo "<settings><servers><server><id>github</id><username>jassu2017</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
        mvn deploy
